[project]
name = "session-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.6.7",
    "fastapi[standard]>=0.116.1",
    "grpcio<1.72.1",
    "openai-agents>=0.2.4",
    "uvicorn>=0.35.0",
]
